apiVersion: v1
kind: Service
metadata:
  name: timelapser-backend-service
  labels:
    app: timelapser-backend
spec:
  selector:
    app: timelapser-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP