apiVersion: v1
kind: Service
metadata:
  name: timelapser-frontend-service
  labels:
    app: timelapser-frontend
spec:
  selector:
    app: timelapser-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP