apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timelapser-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: timelapser.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: timelapser-backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: timelapser-frontend-service
            port:
              number: 3000